//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeBook.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeBook.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на успешно добавлен в программу и в ваш рецепт..
        /// </summary>
        public static string AddNewProductToRecipe {
            get {
                return ResourceManager.GetString("AddNewProductToRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что бы добавить в поиск следующий продукт нажмите Y, что бы завершить добавление продуктов для поиска нажмите N.
        /// </summary>
        public static string AddNextProductOrExit {
            get {
                return ResourceManager.GetString("AddNextProductOrExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  добавлен для поиска..
        /// </summary>
        public static string AddProductForSearch {
            get {
                return ResourceManager.GetString("AddProductForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на успешно добавлен в ваш рецепт..
        /// </summary>
        public static string AddProductToRecipe {
            get {
                return ResourceManager.GetString("AddProductToRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что бы добавить следующий продукт нажмите Y, что бы завершить добавление продуктов нажмите N.
        /// </summary>
        public static string AddTheNextProductOrExit {
            get {
                return ResourceManager.GetString("AddTheNextProductOrExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новый продукт?.
        /// </summary>
        public static string ASKCreateNewProduct {
            get {
                return ResourceManager.GetString("ASKCreateNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите необходимый продукт.
        /// </summary>
        public static string ChooseProduct {
            get {
                return ResourceManager.GetString("ChooseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите продукт который хотите добавить в рецепт:.
        /// </summary>
        public static string ChooseProductForRecipe {
            get {
                return ResourceManager.GetString("ChooseProductForRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите необходимый рецепт.
        /// </summary>
        public static string ChooseRecipe {
            get {
                return ResourceManager.GetString("ChooseRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите меру измерения для данного продукта.
        /// </summary>
        public static string ChooseUnitsForProduct {
            get {
                return ResourceManager.GetString("ChooseUnitsForProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Какое количество продукта необходимо в данном рецепте? Указывать в:.
        /// </summary>
        public static string CountOfProductNeaded {
            get {
                return ResourceManager.GetString("CountOfProductNeaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приятного приготовления!.
        /// </summary>
        public static string Enjoy_your_meal {
            get {
                return ResourceManager.GetString("Enjoy your meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название (или часть названия) продукта:.
        /// </summary>
        public static string Enter_product_name {
            get {
                return ResourceManager.GetString("Enter product name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название (или часть названия) рецепта:.
        /// </summary>
        public static string Enter_recipe_name {
            get {
                return ResourceManager.GetString("Enter recipe name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название нового продукта:.
        /// </summary>
        public static string EnterNameofNewProduct {
            get {
                return ResourceManager.GetString("EnterNameofNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название нового рецепта:.
        /// </summary>
        public static string EnterNameofNewRecipe {
            get {
                return ResourceManager.GetString("EnterNameofNewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название продукта.
        /// </summary>
        public static string EnterProductName {
            get {
                return ResourceManager.GetString("EnterProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите описание процесса приготовления для рецепта.
        /// </summary>
        public static string EnterRecipeDescription {
            get {
                return ResourceManager.GetString("EnterRecipeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите Y или N.
        /// </summary>
        public static string EnterYorN {
            get {
                return ResourceManager.GetString("EnterYorN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти рецепт.
        /// </summary>
        public static string FirstMainMenuItem {
            get {
                return ResourceManager.GetString("FirstMainMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти рецепт по названию.
        /// </summary>
        public static string FirstSecondaryMenuItem {
            get {
                return ResourceManager.GetString("FirstSecondaryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено продуктов:.
        /// </summary>
        public static string Found_Products_Count {
            get {
                return ResourceManager.GetString("Found Products Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено рецептов: .
        /// </summary>
        public static string Found_Recipes_Count {
            get {
                return ResourceManager.GetString("Found Recipes Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено рецептов с данными продуктами:.
        /// </summary>
        public static string FoundRecipeCount {
            get {
                return ResourceManager.GetString("FoundRecipeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грамм.
        /// </summary>
        public static string Gram {
            get {
                return ResourceManager.GetString("Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грамм.
        /// </summary>
        public static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в книгу рецептов 2022!.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сделайте коректный выбор в меню.
        /// </summary>
        public static string IncorrectMenuChoise {
            get {
                return ResourceManager.GetString("IncorrectMenuChoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единиц.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Килограмм.
        /// </summary>
        public static string Kilogram {
            get {
                return ResourceManager.GetString("Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Килограмм.
        /// </summary>
        public static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Литр.
        /// </summary>
        public static string Liter {
            get {
                return ResourceManager.GetString("Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Литров.
        /// </summary>
        public static string Litres {
            get {
                return ResourceManager.GetString("Litres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главное меню:.
        /// </summary>
        public static string MainMenuHeader {
            get {
                return ResourceManager.GetString("MainMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Миллилитр.
        /// </summary>
        public static string Milliliter {
            get {
                return ResourceManager.GetString("Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Миллилитров.
        /// </summary>
        public static string Milliliters {
            get {
                return ResourceManager.GetString("Milliliters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо более точное название..
        /// </summary>
        public static string More_Precise_name_is_required {
            get {
                return ResourceManager.GetString("More Precise name is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый продукт.
        /// </summary>
        public static string NewProduct {
            get {
                return ResourceManager.GetString("NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По вкусу.
        /// </summary>
        public static string PerTaste {
            get {
                return ResourceManager.GetString("PerTaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  уже был добавлен для поиска. Повторите попытку..
        /// </summary>
        public static string ProductAlreadyAddedToSearch {
            get {
                return ResourceManager.GetString("ProductAlreadyAddedToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный продукт уже существует.
        /// </summary>
        public static string ProductAlreadyExist {
            get {
                return ResourceManager.GetString("ProductAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный продукт существует.
        /// </summary>
        public static string ProductExist {
            get {
                return ResourceManager.GetString("ProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данного продукта не существует.
        /// </summary>
        public static string ProductIsNotExist {
            get {
                return ResourceManager.GetString("ProductIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш рецепт создан и добавлен в базу программы..
        /// </summary>
        public static string RecipeWasAddedtoDB {
            get {
                return ResourceManager.GetString("RecipeWasAddedtoDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить свой рецепт.
        /// </summary>
        public static string SecondMainMenuItem {
            get {
                return ResourceManager.GetString("SecondMainMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы выбрали найти рецепт.
        /// </summary>
        public static string SecondMenuHeader {
            get {
                return ResourceManager.GetString("SecondMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти рецепт по составным продуктам.
        /// </summary>
        public static string SecondSecondaryMenuItem {
            get {
                return ResourceManager.GetString("SecondSecondaryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось найти рецепт с данной комбинацией продуктов:.
        /// </summary>
        public static string SuchRecipeNotExist {
            get {
                return ResourceManager.GetString("SuchRecipeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Столовая ложка.
        /// </summary>
        public static string Tablespoon {
            get {
                return ResourceManager.GetString("Tablespoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Столовых ложек.
        /// </summary>
        public static string Tablespoons {
            get {
                return ResourceManager.GetString("Tablespoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попробуйте еще раз..
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
    }
}
